name: Java CI with Maven

on:
  push:
    branches:
      - feature-branch-tests
  pull_request:
    branches:
      - feature-branch-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven lcov

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build backend project
        run: mvn install -DskipTests -f backend/pom.xml

      - name: Run tests and generate coverage report
        run: mvn test jacoco:report -f backend/pom.xml

      - name: Convert JaCoCo XML to LCOV
        run: |
          git clone https://github.com/t-yuki/gocov-xml.git
          cd gocov-xml
          go build
          ./gocov-xml backend/target/site/jacoco/jacoco.xml > backend/target/site/jacoco/coverage.json

      - name: Generate coverage summary
        run: |
          mkdir -p coverage
          genhtml -o coverage --prefix $(pwd) backend/target/site/jacoco/jacoco.xml
          cp coverage/index.html coverage/coverage-summary.json

      - name: Install check-code-coverage
        run: npm i -D check-code-coverage

      - name: Set code coverage commit status
        run: npx -p check-code-coverage set-gh-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
