name: Java CI with Maven

on:
  push:
    branches:
      - main
      - feature-branch-tests
  pull_request:
    branches:
      - main
      - feature-branch-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Navigate to backend directory
        run: cd backend

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: cd backend && mvn install -DskipTests

      - name: Run tests
        run: cd backend && mvn test

      - name: Gather logs on failure
        if: failure()
        run: |
          echo "Build failed. Displaying log files..."
          find . -name "*.log" | xargs cat
