name: Java CI with Maven

on:
  push:
    branches:
      - feature-branch-tests
  pull_request:
    branches:
      - feature-branch-tests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build common module
        run: mvn install -f path/to/common/pom.xml

      - name: Build backend project
        run: mvn install -DskipTests -f backend/pom.xml

      - name: Run test
